name: Initialize Fork

on: 
  workflow_dispatch:
    inputs:
      language:
        description: 'Language to initialize (e.g., kotlin, java)'
        required: true
        default: 'kotlin'

permissions:
  contents: write

jobs:
  setup-fork:
    runs-on: ubuntu-latest
    env:
      PARENT_REPO: "Galaxia5987/frc-train"
      
    steps:
      - name: Exit if Parent Repo
        if: github.repository == env.PARENT_REPO
        run: |
            echo "Error: This is the parent repository. Stopping workflow."
            exit 1
        
      - name: Checkout child repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        env:
          GH_TOKEN: ${{ secrets.USER_PAT }}
        run: |
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Task Initialization & PR Creation
        env:
          LANGUAGE: ${{ github.event.inputs.language }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.USER_PAT }}
        run: node init_fork/index.js